library identifier: "pipeline-library@v1.5",
retriever: modernSCM(
  [
    $class: "GitSCMSource",
    remote: "https://github.com/redhat-cop/pipeline-library.git" 
  ]
)

 

appName = "frontend-buildconfig"

 

pipeline {
    agent any
    stages {
        stage("Checkout") {
            steps {
                checkout scm
            }
        }

        stage("Docker build frontend"){
            steps {
                binaryBuild(buildConfigName: appName, buildFromPath: "./client")
            }
        }

       stage("Tag image") {
       steps{
    tagImage([
            sourceImagePath: "amisha-jenkins",
            sourceImageName: "frontend",
            sourceImageTag : "latest",
            toImagePath: "amisha-jenkins",
            toImageName    : "frontend",
            toImageTag     : "${env.BUILD_NUMBER}"

    ])
       }
       }
      
      stage("Trigger Deployment Update Pipeline"){
        steps{
          build job:'tag-popeline' , parameters: [string(name: 'TAG',value: env.BUILD_NUMBER)]
        }
      }
       
      stage("deploy frontend") {
        steps {
            script {
                openshift.withCluster() {
                    openshift.withProject("$PROJECT_NAME") {
                         sh 'sh -x $WORKSPACE/client/frontend-deployment.sh'
                    }
                }
            }
        } 
    }
    }
}

